import img0 from '../assets/img/Camposol.png';
import img1 from '../assets/img/CN1.png';
import img2 from '../assets/img/CN2.png';
import img3 from '../assets/img/CN3.png';
import img4 from '../assets/img/CN4.png';
import img5 from '../assets/img/CN5.png';
import img6 from '../assets/img/CN6.png';
import img7 from '../assets/img/campo.png';
import img8 from '../assets/img/nube.png';
import img9 from '../assets/img/nube2.png';
import img10 from '../assets/img/nube3.png';
import img11 from '../assets/img/img404.jpg';

export const CN1 = img1;
export const CN2 = img2;
export const CN3 = img3;
export const CN4 = img4;
export const CN5 = img5;
export const CN6 = img6;
export const campo = img7;
export const nube1 = img8;
export const nube2 = img9;
export const nube3 = img10;
export const logo = img0;
export const img404 = img11;